### ISSUE TITLE
define MiVideo table relationships

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/course-inventory#183] opened 2020-05-27 22:06 UTC
MiVideo tables need foreign key relationships to ensure data integrity.

For example:
* [ ] mivideo_media_created.id → mivideo_media_courses.media_id

---

**_Update_**: This had been discussed by @ssciolla, @lsloan, and others in the past.  It was determined that relationships between MiVideo and other tables would break when updates were made, causing errors.  As Sam notes below, it makes sense to establish the relationship between `mivideo_media_created` and `mivideo_media_courses`.

**Comment by ssciolla** [comment] 2020-05-28 18:26
@zqian, establishing foreign keys from MiVideo to the Canvas data tables cannot yet be done easily because we are dropping records in `inventory` and MiVideo does not. If we switch to an update (or upsert) approach for Canvas tables, we can probably make this happen. In this respect, this issue is a duplicate of #162.

However, you are right that we are missing a foreign key between `mivideo_media_created` and `mivideo_media_courses`. This can and should be added.

**Comment by lsloan** [comment] 2020-06-02 20:07
@zqian, I've updated the issue description above.  Of the two examples you gave, @ssciolla and I agree that relationships between MiVideo tables can be maintained.  However, other relationships are problematic.  If you have any other relationships to suggest, please add them to the list in the description.

**Comment by zqian** [comment] 2020-06-05 03:09
Thanks for the suggestions, @ssciolla and @lsloan. I removed the original FK proposal

**Closed** 2020-06-15 20:43 UTC
Labels: 📈 enhancement, 📹 MiVideo, 🥞 database
